In [ ]:
import pandas as pd

**1. Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы.**

In [ ]:
# Читаем файлы:
titles_r = ['user id', 'item id', 'rating', 'timestamp']
movies = pd.read_csv('u.item.csv', sep='|', encoding='latin-1')
ratings = pd.read_csv('u.data.csv', sep = "\t", names = titles_r, header = None)

In [ ]:
movies.head(2)

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,;;;;;;;;;;;;;;;;;;;;;;;
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0;;;;;;;;;;;;;;;;;;;;;;;,NaN
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0;;;;;;;;;;;;;;;;;;;;;;;,NaN

In [ ]:
movies.columns

Index(['movie id ', ' movie title ', ' release date ', ' video release date ',
       ' IMDb URL ', ' unknown ', ' Action ', ' Adventure ', ' Animation ',
       ' Children's ', ' Comedy ', ' Crime ', ' Documentary ', ' Drama ',
       ' Fantasy ', 'Film-Noir ', ' Horror ', ' Musical ', ' Mystery ',
       ' Romance ', ' Sci-Fi ', ' Thriller ', ' War ', ' Western ',
       ';;;;;;;;;;;;;;;;;;;;;;;'],
      dtype='object')

In [ ]:
# Последний столбец неинформативен, удалим его:
del movies[';;;;;;;;;;;;;;;;;;;;;;;']

In [ ]:
# Также оставим только нули и единицы в столбце 'Western':
movies = movies.replace(to_replace =r';*', value='', regex = True)

In [ ]:
# Приведем заголовки в порядок (чтобы в них не было лишних пробелов):
movies.columns = ['movie_id', 'movie_title', 'release_date', 'video_release_date',
       'IMDb_URL', 'unknown', 'Action', 'Adventure', 'Animation',
       "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [ ]:
movies.head(2)

,movie_id,movie_title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
ratings.head(2)

   user id  item id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742

**2. Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок.**

In [ ]:
# Сгруппируем в датафрейме ratings пользователей по их user id и применим функцию для подсчета рейтинга:
def group_func(data):
  return data.rating.count()

In [ ]:
user_max = ratings.groupby('user id').apply(group_func)
user_max.max()

737

In [ ]:
# Определим user id пользователя, который поставил 737 оценок:
user_max[user_max == 737]

user id
405    737
dtype: int64

Это пользователь под номером 405.

**3. Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь.**

In [ ]:
# Сформируем новый датафрейм из строк, для которых user id равен 405:
ratings_405 = ratings[ratings['user id'] == 405]
ratings_405

       user id  item id  rating  timestamp
12276      405       56       4  885544911
12383      405      592       1  885548670
12430      405     1582       1  885548670
12449      405      171       1  885549544
12460      405      580       1  885547447
...        ...      ...     ...        ...
98956      405      375       1  885546835
98978      405      445       4  885548435
99148      405     1246       1  885547735
99465      405      196       1  885546112
99756      405      958       1  885549590

[737 rows x 4 columns]

**4. Добавьте к датафрейму из задания 3 столбцы:**

**По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм принадлежит данному жанру и 0 - если нет
столбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей.**

In [ ]:
movies_c = movies[['movie_id', 'release_date', 'unknown', 'Action', 'Adventure', 'Animation',
       "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery',
       'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

In [ ]:
movies_c.head(2)

,movie_id,release_date,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,01-Jan-1995,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,01-Jan-1995,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# Одним из признаков будет год, получим его их release_date с помощью функции:
from datetime import datetime

def year_func(data):
  return (str(data))[7:11]

In [ ]:
movies_c['release_year'] = movies_c['release_date'].apply(year_func)

<ipython-input-130-7e84f7e36eca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_c['release_year'] = movies_c['release_date'].apply(year_func)

In [ ]:
# Столбцес с датой релиза удалим
del movies_c['release_date']

In [ ]:
# Посмотрим на получившийся датафрейм с частью признаков:
movies_c.head()

,movie_id,unknown,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,release_year
0,1,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
1,2,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1995
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1995
3,4,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1995
4,5,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,1,0,0,1995

In [ ]:
# Подсчитаем количество оценок:
score_count = ratings.groupby('item id').apply(group_func)
score_count

item id
1       452
2       131
3        90
4       209
5        86
       ...
1678      1
1679      1
1680      1
1681      1
1682      1
Length: 1682, dtype: int64

In [ ]:
# Подсчитаем суммарную оценку:
score_sum = ratings.groupby('item id').agg(sum)['rating']
score_sum

item id
1       1753
2        420
3        273
4        742
5        284
        ...
1678       1
1679       3
1680       2
1681       3
1682       3
Name: rating, Length: 1682, dtype: int64

In [ ]:
# Из полученных наборов значений соберем датафрейм scores:
scores = pd.DataFrame({'score_count' : score_count, 'score_sum' : score_sum})
scores

         score_count  score_sum
item id
1                452       1753
2                131        420
3                 90        273
4                209        742
5                 86        284
...              ...        ...
1678               1          1
1679               1          3
1680               1          2
1681               1          3
1682               1          3

[1682 rows x 2 columns]

In [ ]:
# Объединим датафрейм scores с датафреймом с фильмами, которые оценивал пользователь 405 (за одно отфильтруем лишних пользователей):
df_405 = ratings_405.merge(scores, how='left', on='item id')
df_405

     user id  item id  rating  timestamp  score_count  score_sum
0        405       56       4  885544911          394       1600
1        405      592       1  885548670            9         30
2        405     1582       1  885548670            1          1
3        405      171       1  885549544           65        252
4        405      580       1  885547447           32        108
..       ...      ...     ...        ...          ...        ...
732      405      375       1  885546835           23         45
733      405      445       4  885548435           22         77
734      405     1246       1  885547735            7         11
735      405      196       1  885546112          251        983
736      405      958       1  885549590           14         53

[737 rows x 6 columns]

In [ ]:
# Датафрейм обогатим признаками, собранными ранее в датафрейм movies_c.
df = df_405.merge(movies_c, how='left', left_on='item id', right_on='movie_id')
df

,user id,item id,rating,timestamp,score_count,score_sum,movie_id,unknown,Action,Adventure,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,release_year
0,405,56,4,885544911,394,1600,56,0,0,0,...,0,0,0,0,0,0,0,0,0,1994
1,405,592,1,885548670,9,30,592,0,0,0,...,0,0,0,1,0,0,1,0,0,1995
2,405,1582,1,885548670,1,1,1582,0,0,0,...,1,0,0,0,0,0,0,0,0,1947
3,405,171,1,885549544,65,252,171,0,0,0,...,0,0,0,0,0,1,0,0,0,1991
4,405,580,1,885547447,32,108,580,0,0,0,...,0,0,0,0,1,0,0,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,405,375,1,885546835,23,45,375,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
733,405,445,4,885548435,22,77,445,0,0,0,...,0,1,0,0,0,0,0,0,0,1945
734,405,1246,1,885547735,7,11,1246,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
735,405,196,1,885546112,251,983,196,0,0,0,...,0,0,0,0,0,0,0,0,0,1989
736,405,958,1,885549590,14,53,958,0,0,0,...,0,0,0,0,0,0,0,0,0,1994

In [ ]:
# Столбцы item id и movie_id содержат одни и те же значения, оставим только один из них:
del df['item id']

In [ ]:
# Столбцец с меткой времени тоже не понадобится:
del df['timestamp']

In [ ]:
# В результате датафрейм примет следующий вид:
df.head()

,user id,rating,score_count,score_sum,movie_id,unknown,Action,Adventure,Animation,Children's,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,release_year
0,405,4,394,1600,56,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1994
1,405,1,9,30,592,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1995
2,405,1,1,1,1582,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1947
3,405,1,65,252,171,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1991
4,405,1,32,108,580,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1995

In [ ]:
# Информация о датафрейме df:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737 entries, 0 to 736
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user id       737 non-null    int64
 1   rating        737 non-null    int64
 2   score_count   737 non-null    int64
 3   score_sum     737 non-null    int64
 4   movie_id      737 non-null    int64
 5   unknown       737 non-null    int64
 6   Action        737 non-null    int64
 7   Adventure     737 non-null    int64
 8   Animation     737 non-null    int64
 9   Children's    737 non-null    int64
 10  Comedy        737 non-null    int64
 11  Crime         737 non-null    int64
 12  Documentary   737 non-null    int64
 13  Drama         737 non-null    int64
 14  Fantasy       737 non-null    int64
 15  Film-Noir     737 non-null    int64
 16  Horror        737 non-null    int64
 17  Musical       737 non-null    int64
 18  Mystery       737 non-null    int64
 19  Romance       737 non-null    int64
 20  Sci-Fi        737 non-null    int64
 21  Thriller      737 non-null    int64
 22  War           737 non-null    int64
 23  Western       737 non-null    object
 24  release_year  737 non-null    object
dtypes: int64(23), object(2)
memory usage: 149.7+ KB

In [ ]:
# Данные в столбцах Western и release_year имеют тип 'object', преобразуем их в 'int'.
import numpy as np

In [ ]:
df = df.astype({'Western':np.int64,'release_year':np.int64})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737 entries, 0 to 736
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user id       737 non-null    int64
 1   rating        737 non-null    int64
 2   score_count   737 non-null    int64
 3   score_sum     737 non-null    int64
 4   movie_id      737 non-null    int64
 5   unknown       737 non-null    int64
 6   Action        737 non-null    int64
 7   Adventure     737 non-null    int64
 8   Animation     737 non-null    int64
 9   Children's    737 non-null    int64
 10  Comedy        737 non-null    int64
 11  Crime         737 non-null    int64
 12  Documentary   737 non-null    int64
 13  Drama         737 non-null    int64
 14  Fantasy       737 non-null    int64
 15  Film-Noir     737 non-null    int64
 16  Horror        737 non-null    int64
 17  Musical       737 non-null    int64
 18  Mystery       737 non-null    int64
 19  Romance       737 non-null    int64
 20  Sci-Fi        737 non-null    int64
 21  Thriller      737 non-null    int64
 22  War           737 non-null    int64
 23  Western       737 non-null    int64
 24  release_year  737 non-null    int64
dtypes: int64(25)
memory usage: 149.7 KB

**5. Сформируйте X_train, X_test, y_train, y_test.**

In [ ]:
df.columns

Index(['user id', 'rating', 'score_count', 'score_sum', 'movie_id', 'unknown',
       'Action', 'Adventure', 'Animation', 'Children's', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western',
       'release_year'],
      dtype='object')

In [ ]:
# Целевая переменная - оценка фильма пользователем; остальные переменные - признаки.
X, y = df[['movie_id', 'score_count', 'score_sum', 'unknown',
       'Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western',
       'release_year']], df['rating']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

**6. Возьмите модель линейной регрессии (или любую другую для задачи регрессии)  и обучите ее на фильмах.**

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

**7. Оцените качество модели на X_test, y_test при помощи метрик для задачи регрессии.**

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test, y_pred)

1.550252419324584

Ошибка получается небольшая.

Применим модель логистической регрессии:

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model_2 = LogisticRegression()

In [ ]:
model_2.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
# Оценим точность предсказания:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_train, model_2.predict(X_train))

0.6865942028985508

In [ ]:
accuracy_score(y_test, model_2.predict(X_test))

0.6486486486486487

**Вывод: точность предсказания оценки фильма около 66%, что неплохо.**

# **Вторая часть практики Python связана со Spark’ом**

In [ ]:
!apt-get update

Get:1 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:3 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease [18.1 kB]
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64  InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease [1,581 B]
Hit:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64  Release
Get:8 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Get:13 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages [869 kB]
Get:15 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal/main Sources [2,381 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,291 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,921 kB]
Get:18 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal/main amd64 Packages [1,128 kB]
Get:19 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [990 kB]
Get:20 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,448 kB]
Fetched 12.4 MB in 4s (2,817 kB/s)
Reading package lists... Done

In [ ]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [ ]:
!wget -q https://downloads.apache.org/spark/spark-3.2.3/spark-3.2.3-bin-hadoop2.7.tgz

In [ ]:
!tar -xvf spark-3.2.3-bin-hadoop2.7.tgz

spark-3.2.3-bin-hadoop2.7/
spark-3.2.3-bin-hadoop2.7/LICENSE
spark-3.2.3-bin-hadoop2.7/NOTICE
spark-3.2.3-bin-hadoop2.7/R/
spark-3.2.3-bin-hadoop2.7/R/lib/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/DESCRIPTION
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/INDEX
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/Rd.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/features.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/hsearch.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/links.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/nsInfo.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/Meta/package.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/NAMESPACE
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/SparkR
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdb
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdx
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/AnIndex
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdb
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdx
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/aliases.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/help/paths.rds
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/html/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/html/00Index.html
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/html/R.css
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/profile/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/profile/general.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/profile/shell.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/tests/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/tests/testthat/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/worker/
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/worker/daemon.R
spark-3.2.3-bin-hadoop2.7/R/lib/SparkR/worker/worker.R
spark-3.2.3-bin-hadoop2.7/R/lib/sparkr.zip
spark-3.2.3-bin-hadoop2.7/README.md
spark-3.2.3-bin-hadoop2.7/RELEASE
spark-3.2.3-bin-hadoop2.7/bin/
spark-3.2.3-bin-hadoop2.7/bin/beeline
spark-3.2.3-bin-hadoop2.7/bin/beeline.cmd
spark-3.2.3-bin-hadoop2.7/bin/docker-image-tool.sh
spark-3.2.3-bin-hadoop2.7/bin/find-spark-home
spark-3.2.3-bin-hadoop2.7/bin/find-spark-home.cmd
spark-3.2.3-bin-hadoop2.7/bin/load-spark-env.cmd
spark-3.2.3-bin-hadoop2.7/bin/load-spark-env.sh
spark-3.2.3-bin-hadoop2.7/bin/pyspark
spark-3.2.3-bin-hadoop2.7/bin/pyspark.cmd
spark-3.2.3-bin-hadoop2.7/bin/pyspark2.cmd
spark-3.2.3-bin-hadoop2.7/bin/run-example
spark-3.2.3-bin-hadoop2.7/bin/run-example.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-class
spark-3.2.3-bin-hadoop2.7/bin/spark-class.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-class2.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-shell
spark-3.2.3-bin-hadoop2.7/bin/spark-shell.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-shell2.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-sql
spark-3.2.3-bin-hadoop2.7/bin/spark-sql.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-sql2.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-submit
spark-3.2.3-bin-hadoop2.7/bin/spark-submit.cmd
spark-3.2.3-bin-hadoop2.7/bin/spark-submit2.cmd
spark-3.2.3-bin-hadoop2.7/bin/sparkR
spark-3.2.3-bin-hadoop2.7/bin/sparkR.cmd
spark-3.2.3-bin-hadoop2.7/bin/sparkR2.cmd
spark-3.2.3-bin-hadoop2.7/conf/
spark-3.2.3-bin-hadoop2.7/conf/fairscheduler.xml.template
spark-3.2.3-bin-hadoop2.7/conf/log4j.properties.template
spark-3.2.3-bin-hadoop2.7/conf/metrics.properties.template
spark-3.2.3-bin-hadoop2.7/conf/spark-defaults.conf.template
spark-3.2.3-bin-hadoop2.7/conf/spark-env.sh.template
spark-3.2.3-bin-hadoop2.7/conf/workers.template
spark-3.2.3-bin-hadoop2.7/data/
spark-3.2.3-bin-hadoop2.7/data/graphx/
spark-3.2.3-bin-hadoop2.7/data/graphx/followers.txt
spark-3.2.3-bin-hadoop2.7/data/graphx/users.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/
spark-3.2.3-bin-hadoop2.7/data/mllib/als/
spark-3.2.3-bin-hadoop2.7/data/mllib/als/sample_movielens_ratings.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/als/test.data
spark-3.2.3-bin-hadoop2.7/data/mllib/gmm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/license.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/54893.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/kittens/not-image.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/license.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/29.5.a_b_EGDP022204.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-01/not-image.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/54893.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP153539.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP802813.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA_alpha_60.png
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/chr30.4.184.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/grayscale.jpg
spark-3.2.3-bin-hadoop2.7/data/mllib/iris_libsvm.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/kmeans_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/pagerank_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/pic_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/ridge-data/
spark-3.2.3-bin-hadoop2.7/data/mllib/ridge-data/lpsa.data
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_fpgrowth.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_kmeans_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_lda_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_lda_libsvm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_libsvm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_linear_regression_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_movielens_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_multiclass_classification_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/sample_svm_data.txt
spark-3.2.3-bin-hadoop2.7/data/mllib/streaming_kmeans_data_test.txt
spark-3.2.3-bin-hadoop2.7/data/streaming/
spark-3.2.3-bin-hadoop2.7/data/streaming/AFINN-111.txt
spark-3.2.3-bin-hadoop2.7/examples/
spark-3.2.3-bin-hadoop2.7/examples/jars/
spark-3.2.3-bin-hadoop2.7/examples/jars/scopt_2.12-3.7.1.jar
spark-3.2.3-bin-hadoop2.7/examples/jars/spark-examples_2.12-3.2.3.jar
spark-3.2.3-bin-hadoop2.7/examples/src/
spark-3.2.3-bin-hadoop2.7/examples/src/main/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.2.3-bin-hadoop2.7/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java

In [ ]:
!pip install -q findspark

In [ ]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.3-bin-hadoop2.7"

In [ ]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()
sc = spark.sparkContext

**8. Загрузить данные в spark.**

In [ ]:
movies = spark.read.csv('u.item.csv', sep='|', inferSchema=True, header=True)
movies.show()

+---------+--------------------+--------------+--------------------+--------------------+---------+--------+-----------+-----------+------------+--------+-------+-------------+-------+---------+----------+--------+---------+---------+---------+--------+----------+-----+--------------------+-----------------------+
|movie id |        movie title | release date | video release date |           IMDb URL | unknown | Action | Adventure | Animation | Children's | Comedy | Crime | Documentary | Drama | Fantasy |Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | Thriller | War |            Western |;;;;;;;;;;;;;;;;;;;;;;;|
+---------+--------------------+--------------+--------------------+--------------------+---------+--------+-----------+-----------+------------+--------+-------+-------------+-------+---------+----------+--------+---------+---------+---------+--------+----------+-----+--------------------+-----------------------+
|        1|    Toy Story (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          1|           1|       1|      0|            0|      0|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        2|    GoldenEye (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       1|          1|          0|           0|       0|      0|            0|      0|        0|         0|       0|        0|        0|        0|       0|         1|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        3|   Four Rooms (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      0|        0|         0|       0|        0|        0|        0|       0|         1|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        4|   Get Shorty (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       1|          0|          0|           0|       1|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        5|      Copycat (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      1|            0|      1|        0|         0|       0|        0|        0|        0|       0|         1|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        6|Shanghai Triad (Y...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        7|Twelve Monkeys (1...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       1|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        8|         Babe (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           1|       1|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|        9|Dead Man Walking ...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       10|  Richard III (1995)|   22-Jan-1996|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    1|0;;;;;;;;;;;;;;;;...|                   null|
|       11|Seven (Se7en) (1995)|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      1|            0|      0|        0|         0|       0|        0|        0|        0|       0|         1|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       12|Usual Suspects, T...|   14-Aug-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      1|            0|      0|        0|         0|       0|        0|        0|        0|       0|         1|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       13|Mighty Aphrodite ...|   30-Oct-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       1|      0|            0|      0|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       14|  Postino, Il (1994)|   01-Jan-1994|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        1|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       15|Mr. Holland's Opu...|   29-Jan-1996|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       16|French Twist (Gaz...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       1|      0|            0|      0|        0|         0|       0|        0|        0|        1|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       17|From Dusk Till Da...|   05-Feb-1996|                null|http://us.imdb.co...|        0|       1|          0|          0|           0|       1|      1|            0|      0|        0|         0|       1|        0|        0|        0|       0|         1|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       18|White Balloon, Th...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       19|Antonia's Line (1...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        0|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
|       20|Angels and Insect...|   01-Jan-1995|                null|http://us.imdb.co...|        0|       0|          0|          0|           0|       0|      0|            0|      1|        0|         0|       0|        0|        0|        1|       0|         0|    0|0;;;;;;;;;;;;;;;;...|                   null|
+---------+--------------------+--------------+--------------------+--------------------+---------+--------+-----------+-----------+------------+--------+-------+-------------+-------+---------+----------+--------+---------+---------+---------+--------+----------+-----+--------------------+-----------------------+
only showing top 20 rows

In [ ]:
ratings = spark.read.csv('u.data.csv', sep="\t", inferSchema=True, header=False)
ratings = ratings.toDF('user id', 'item id', 'rating', 'timestamp')
ratings.show()

+-------+-------+------+---------+
|user id|item id|rating|timestamp|
+-------+-------+------+---------+
|    196|    242|     3|881250949|
|    186|    302|     3|891717742|
|     22|    377|     1|878887116|
|    244|     51|     2|880606923|
|    166|    346|     1|886397596|
|    298|    474|     4|884182806|
|    115|    265|     2|881171488|
|    253|    465|     5|891628467|
|    305|    451|     3|886324817|
|      6|     86|     3|883603013|
|     62|    257|     2|879372434|
|    286|   1014|     5|879781125|
|    200|    222|     5|876042340|
|    210|     40|     3|891035994|
|    224|     29|     3|888104457|
|    303|    785|     3|879485318|
|    122|    387|     5|879270459|
|    194|    274|     2|879539794|
|    291|   1042|     4|874834944|
|    234|   1184|     2|892079237|
+-------+-------+------+---------+
only showing top 20 rows

**9. Средствами спарка вывести среднюю оценку для каждого фильма.**

In [ ]:
# Сгруппируем фильмы по номеру (item id) и для каждого посчитаем среднюю оценку:
df_mean_score = ratings.groupby('item id').avg('rating')
df_mean_score.show()

+-------+------------------+
|item id|       avg(rating)|
+-------+------------------+
|    496| 4.121212121212121|
|    471|3.6108597285067874|
|    463| 3.859154929577465|
|    148|          3.203125|
|   1342|               2.5|
|    833| 3.204081632653061|
|   1088| 2.230769230769231|
|   1591|3.1666666666666665|
|   1238|             3.125|
|   1580|               1.0|
|   1645|               4.0|
|    392|3.5441176470588234|
|    623| 2.923076923076923|
|    540| 2.511627906976744|
|    858|               1.0|
|    737| 2.983050847457627|
|    243|2.4393939393939394|
|   1025|2.9318181818181817|
|   1084| 3.857142857142857|
|   1127| 2.909090909090909|
+-------+------------------+
only showing top 20 rows

**10. В спарке получить 2 датафрейма с 5-ю самыми популярными и самыми непопулярными фильмами (по количеству оценок, либо по самой оценке - на Ваш выбор).**

In [ ]:
# Top-5 самых популярных фильмов по количеству оценок:
top5_best = ratings.groupby('item id').count()
top5_best.sort(top5_best['count'].desc()).show(5)

+-------+-----+
|item id|count|
+-------+-----+
|     50|  583|
|    258|  509|
|    100|  508|
|    181|  507|
|    294|  485|
+-------+-----+
only showing top 5 rows

In [ ]:
# Top-5 самых непопулярных фильмов по количеству оценок:
top5_worst = ratings.groupby('item id').count()
top5_worst.sort(top5_worst['count'].asc()).show(5)
# На самом деле фильмов, которым выставлено по одной оценке, гораздо больше пяти.

+-------+-----+
|item id|count|
+-------+-----+
|   1460|    1|
|   1618|    1|
|   1339|    1|
|   1645|    1|
|   1650|    1|
+-------+-----+
only showing top 5 rows

In [ ]:
# Возможно, информативнее будут датафреймы, фильмы в которых отсортированы по среднему рейтингу.
top_avg = df_mean_score.sort(df_mean_score['avg(rating)'].desc())
top_avg.show()

+-------+-----------------+
|item id|      avg(rating)|
+-------+-----------------+
|   1467|              5.0|
|   1599|              5.0|
|   1122|              5.0|
|   1500|              5.0|
|   1189|              5.0|
|   1293|              5.0|
|   1201|              5.0|
|   1536|              5.0|
|    814|              5.0|
|   1653|              5.0|
|   1449|            4.625|
|   1398|              4.5|
|   1594|              4.5|
|    119|              4.5|
|   1642|              4.5|
|    408|4.491071428571429|
|    318|4.466442953020135|
|    169|4.466101694915254|
|    483| 4.45679012345679|
|    114|4.447761194029851|
+-------+-----------------+
only showing top 20 rows

In [ ]:
# Фильмов с самым высоким средним рейтингом 10 шт.:
top10_avg_best = top_avg
top10_avg_best.show(10)

+-------+-----------+
|item id|avg(rating)|
+-------+-----------+
|   1599|        5.0|
|   1201|        5.0|
|   1653|        5.0|
|   1500|        5.0|
|   1467|        5.0|
|   1189|        5.0|
|   1293|        5.0|
|   1536|        5.0|
|    814|        5.0|
|   1122|        5.0|
+-------+-----------+
only showing top 10 rows

In [ ]:
# И 10 фильмов с самым низким средним рейтингом (таких фильмов больше 10-ти):
top10_avg_worst = df_mean_score.sort(df_mean_score['avg(rating)'].asc())
top10_avg_worst.show(10)

+-------+-----------+
|item id|avg(rating)|
+-------+-----------+
|   1621|        1.0|
|   1582|        1.0|
|    784|        1.0|
|    858|        1.0|
|   1618|        1.0|
|   1574|        1.0|
|   1352|        1.0|
|   1493|        1.0|
|   1561|        1.0|
|   1363|        1.0|
+-------+-----------+
only showing top 10 rows